---
title: "disbudding_analysis"
author: "Hannah Phillips"
date: "April 10, 2020"
output: html_document
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = T, messages = F, warning = F)
library(readxl)
library(tidyverse)
library(dplyr)
library(nlme) #lme model
library(lme4) #lmer
library(lmerTest) # KR ddf
library(afex) #CIs
library(emmeans) #lsmeans
library(glmmTMB) #glmm
library(ggplot2)
library(psych) #describe

#theme_get()

theme_set(
  theme_bw() +
    theme(plot.title = element_text(hjust = .5))
)
```

# Cortisol analysis
```{r, include = F}
#Input data
dat <- 
  read_excel("C:/Users/Hannah/Desktop/Disbudding project/disbudding_R_project/cortisol_data.xlsx", sheet = "Data") %>%
  mutate_at(vars(ID, Treatment, Hutch, Breed, Minute), as.factor)

baseline_dat <- dat %>%
  filter(Minute == "-10")

#Create baseline cortisol variable, impute mean baseline value for missing observations
mean_baseline <- mean(filter(dat, Minute == "-10")$Cortisol, na.rm = T)

dat <- dat %>%
  mutate(Cortisol = ifelse(is.na(Cortisol) & Minute == "-10", mean_baseline, Cortisol)) %>%
  group_by(ID) %>% 
  mutate(Baseline = Cortisol[Minute == "-10"]) %>%
  filter(Minute != "-10")
```

## Histograms
```{r, echo = T}
#natural scale 
ggplot(dat, aes(Cortisol)) +
  geom_histogram(aes(y = ..density..), binwidth = 2) +
  geom_density() +
  labs(title = "Cortisol histogram on natural scale", x = "Cortisol")

#log transformed
ggplot(dat, aes(log(Cortisol + 1))) +
  geom_histogram(aes(y = ..density..), binwidth = .2) +
  geom_density() +
  labs(title = "Cortisol histogram on log + 1 scale", x = "log(Cortisol + 1)")
```

## Analysis
```{r}
model <- 
  lme(
    log(Cortisol + 1) ~ log(Baseline + 1) + Treatment*Minute, 
    data = dat, 
    random = ~ 1|Hutch/ID, 
    correlation = corCAR1(form = ~ as.numeric(Minute)|Hutch/ID),
    na.action = na.omit
  )

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#output
anova <- anova.lme(model)
anova

summary(model)

#lsmeans
lsmeans <- emmeans(model, ~ Treatment | Minute, type = "response", mode = "auto")
lsmeans

lsmeans_df <- as.data.frame(lsmeans)

#means seperation
confint(
  contrast(regrid(lsmeans, transform = "response"), 
           reverse = F, 
           ratio = F, 
           method = "pairwise"), 
  level = 0.95
)

multcomp::cld(lsmeans, alpha = .05)

remove(model, anova, lsmeans, lsmeans_df)
```

## Baseline analysis
```{r}
model <- 
  lme(
    log(Cortisol + 1) ~ Treatment, 
    data = baseline_dat, 
    random = ~ 1|Hutch,
    na.action = na.omit
  )

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#output
anova <- anova.lme(model)
anova

summary(model)

#lsmeans
lsmeans <- emmeans(model, ~ Treatment, type = "response", mode = "auto")
lsmeans_df <- as.data.frame(lsmeans)

#means seperation
confint(
  contrast(regrid(lsmeans, transform = "response"), 
           reverse = F, 
           ratio = F, 
           method = "pairwise"), 
  level = 0.95
)

multcomp::cld(lsmeans, alpha = .05)

remove(model, anova, lsmeans, lsmeans_df)
```



# Behavior at disbudding
```{r}
#Input data
dat <-
  read_excel("disbudding_behavior_data.xlsx") %>%
  mutate_at(vars(ID, Treatment, Hutch, Breed), as.factor) %>%
  filter(!is.na(Handle_time)) %>%
  mutate(Head_movement = Head_avoidance + Head_stretch)

#make variable a frequency
dat[,12:20] <- dat[,12:20] / dat$Handle_time
```

## Histograms
```{r, echo = F}
#natural scale
plot.1 <- 
  ggplot(dat, aes(Burn_time)) +
  geom_histogram(aes(y = ..density..), binwidth = 1) +
  geom_density() +
  labs(title = NULL, x = "Burn time, s")

plot.2 <- 
  ggplot(dat, aes(Handle_time)) +
  geom_histogram(aes(y = ..density..), binwidth = 2) +
  geom_density() +
  labs(title = NULL, x = "Handle time, s")

plot.3 <- 
  ggplot(dat, aes(Vocal)) +
  geom_histogram(aes(y = ..density..), binwidth = .08) +
  geom_density() +
  labs(title = NULL, x = "Vocalize, count/s")

plot.4 <- 
  ggplot(dat, aes(Kick)) +
  geom_histogram(aes(y = ..density..), binwidth = .08) +
  geom_density() +
  labs(title = NULL, x = "Kick, count/s")

plot.5 <- 
  ggplot(dat, aes(Tail_wag)) +
  geom_histogram(aes(y = ..density..), binwidth = .4) +
  geom_density() +
  labs(title = NULL, x = "Tail_wag, count/s")

plot.6 <- 
  ggplot(dat, aes(Head_movement)) +
  geom_histogram(aes(y = ..density..), binwidth = .08) +
  geom_density() +
  labs(title = NULL, x = "Head movement, count/s")

plot.7 <- 
  ggplot(dat, aes(Force)) +
  geom_histogram(aes(y = ..density..), binwidth = .05) +
  geom_density() +
  labs(title = NULL, x = "Force ahead, count/s")


plots <- cowplot::plot_grid(plot.1, plot.2, plot.3, plot.4, plot.5, plot.6, plot.7)

title <- 
  cowplot::ggdraw() + 
  cowplot::draw_label(
    "Histograms",
    fontface = 'bold',
    x = 0,
    hjust = -1
  ) +
  theme(plot.margin = margin(0, 0, 0, 7))

cowplot::plot_grid(
  title, 
  plots,
  ncol = 1,
  rel_heights = c(0.1, 1)
)
```

## Summary of data
```{r}
summary <- describe(dat[, 10:20], fast = T) %>%
  mutate(var = sd^2) %>%
  mutate_if(is.numeric, round, digits = 2)

summary <- cbind(vars = rownames(describe(dat[, 10:20], fast = T)), summary)
```


## Analyses
### Burn time
```{r}
model <- 
  lmer(
    Burn_time ~ 1 + Treatment + (1|Hutch), 
    data = dat
  )

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#output
anova <- anova(model, ddf = "Kenward-Roger")
anova

summary(model, ddf = "Kenward-Roger")

#lsmeans
lsmeans <- emmeans(model, ~ Treatment, type = "response", mode = "kenward-roger")
lsmeans_df <- as.data.frame(lsmeans)

#means seperation
confint(
  contrast(regrid(lsmeans, transform = "response"), 
           reverse = F, 
           ratio = F, 
           method = "pairwise"), 
  level = 0.95
)

multcomp::cld(lsmeans, alpha = .05)

remove(model, anova, lsmeans, lsmeans_df)
```

### Burn time
```{r}
model <- 
  lmer(
    Burn_time ~ 1 + Treatment + (1|Hutch), 
    data = dat
  )

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#output
anova <- anova(model, ddf = "Kenward-Roger")
anova

summary(model, ddf = "Kenward-Roger")

#lsmeans
lsmeans <- emmeans(model, ~ Treatment, type = "response", mode = "kenward-roger")
lsmeans_df <- as.data.frame(lsmeans)

#means seperation
confint(
  contrast(regrid(lsmeans, transform = "response"), 
           reverse = F, 
           ratio = F, 
           method = "pairwise"), 
  level = 0.95
)

multcomp::cld(lsmeans, alpha = .05)

remove(model, anova, lsmeans, lsmeans_df)
```